steps:
  - name: hashicorp/terraform:latest
    entrypoint: 'sh'
    args: 
     - '-c'
     - | 
        git clone --branch seemlessflow https://github.com/anup1987/IngramMicroTerraform.git
        cd IngramMicroTerraform
        git branch
        cd modules/cloud_run
        pwd
        terraform init -backend=true -backend-config="gcs" -backend-config="project=ingrammicroproject" -backend-config="path=terraform.tfstate"
        terraform apply -var="imagename=gcr.io/ingrammicroproject/hellospringwebapplication:latest"  -var="serviceName=app1" -auto-approve
        ls -lart
