steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/hellospringwebapplication", "--build-arg=JAR_FILE=target/helloworld-0.0.1-SNAPSHOT.jar", "."]
# [START tf-apply]
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args: 
     - '-c'
     - | 
        git clone https://github.com/anup1987/IngramMicroTerraform.git
        cd IngramMicroTerraform
        git checkout -b gcp
        git pull origin gcp
        cd modules/cloud_run
        terraform init
        terraform apply -var="project_id=ingrammicroproject" -var="imagename=hellospringwebapplication"  -var="deploy_run_service_name=hellospringwebapplication" -auto-approved     
# [END tf-apply]  
images: ["gcr.io/$PROJECT_ID/hellospringwebapplication"]
